# This is a basic workflow that is manually triggered

name: 01a ejercicio hola mundo

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  hola-mundo:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps:
      - name: Hello man exercise
        run: echo "Hello man exercise"
